### ISSUE TITLE
Bug: Cannot load scripts

### ISSUE THREAD

**Issue by Windos** [ironmansoftware/universal-automation-desktop#1]
On the first (auto) launch after installing UAD, I'm not able to upload a script:

![2020-02-25](https://user-images.githubusercontent.com/6955786/75192229-af9b2200-57b8-11ea-8177-85f35dd492ac.png)

Also, clicking the "Open Script Folder" does nothing.

This persists after closing and re-open the app (including exiting via the tray icon).

This persists even if I run the app as admin.

## Details

![WinVer](https://user-images.githubusercontent.com/6955786/75192310-df4a2a00-57b8-11ea-83fe-b310c8a996ff.png)

```
PS C:\> $PSVersionTable

Name                           Value                                                                                                                                                           
----                           -----                                                                                                                                                           
PSVersion                      5.1.18362.628                                                                                                                                                   
PSEdition                      Desktop                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                         
BuildVersion                   10.0.18362.628                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                             
SerializationVersion           1.1.0.1      
```

I'm a Azure AD joined user on this machine, and local admin, if that makes any difference.

**Comment by adamdriscoll** [comment]
@Windos - Did this box have an existing UA instance on it before running UAD?

**Comment by Windos** [comment]
Oh... I'm not 100% sure, but it's quite likely I did some UA testing on this machine previously

**Comment by Windos** [comment]
Just uninstalled UAD, removed the two UA* folders in my local app data, then re-installed (imagine I didn't need to do *all of that?)

It's now working 😄 

![Working UAD](https://user-images.githubusercontent.com/6955786/75280646-b2f2e400-5872-11ea-9160-c66f1788a062.png)

**Comment by adamdriscoll** [comment]
It's likely that the UA server was configured previously with auth and then the UA desktop fails to connect because of this. It probably should have a better error message.

**Comment by Windos** [comment]
Yeah, that'd be great. Especially at this early stage I image there'd be a few in my position. Could also see someone trying UA server and moving over to UAD down the line.
